{{- if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.backup.storage.class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
{{- end }}
